import type { Procedure } from "@/types/engine";

/**
 * German Procedures — v1
 *
 * Every procedure tagged with country: "DE" so the engine can filter.
 * When NL/AT/CH ship, they live in their own files (procedures-nl.ts, etc.)
 * and the index combines them.
 */

export const proceduresDE: Procedure[] = [
  {
    id: "anabin_check",
    country: "DE",
    nameDe: "Anabin-Anerkennung",
    nameEn: "Degree recognition (anabin)",
    description: "Verify your university degree is recognized in Germany via the anabin database. Required for Blue Card.",
    phase: "pre-arrival",
    appliesWhen: {
      type: "and",
      clauses: [
        { type: "nationality_not_in", values: ["EU"] },
        { type: "has_visa_in", values: ["blue-card", "work-permit"] },
      ],
    },
    prerequisites: [],
    produces: ["anabin_confirmation"],
    deadline: { type: "before_procedure", procedureId: "blue_card_visa", days: 14 },
    processingTime: { minDays: 0, maxDays: 0, notes: "Instant database lookup" },
    locationDependent: false,
    costEur: 0,
    documentsRequired: ["University degree certificate", "Transcript"],
    officialUrl: "https://anabin.kmk.org/",
    escapePaths: [
      {
        id: "anabin_no_match",
        whenBlocked: "Degree not in anabin or marked H- / H+/-",
        resolution: "Apply to ZAB for a Zeugnisbewertung — costs ~€200, takes 3 months.",
      },
    ],
    xpReward: 30,
    badgeId: "first_step",
    lastVerified: "2026-04",
    verificationSource: "Claude general knowledge — REQUIRES expert review",
  },
  {
    id: "blue_card_visa",
    country: "DE",
    nameDe: "Blaue-Karte-Visum",
    nameEn: "Blue Card entry visa",
    description: "EU Blue Card entry visa, applied for at the German consulate in your home country.",
    phase: "pre-arrival",
    appliesWhen: {
      type: "and",
      clauses: [
        { type: "nationality_not_in", values: ["EU"] },
        { type: "has_visa_in", values: ["blue-card"] },
      ],
    },
    prerequisites: ["anabin_check"],
    produces: ["entry_visa_sticker"],
    deadline: { type: "none" },
    processingTime: { minDays: 14, maxDays: 90 },
    locationDependent: false,
    costEur: 75,
    documentsRequired: [
      "Signed employment contract",
      "Salary proof (Blue Card threshold: €58,400 / €48,300 shortage occupation)",
      "Recognized degree (anabin H+)",
      "Travel health insurance",
      "Biometric photos",
    ],
    bookingUrl: "https://service2.diplo.de/rktermin/extern/choose_realmList.do",
    escapePaths: [
      {
        id: "no_appointment_slots",
        whenBlocked: "No consulate appointments within hiring timeline",
        resolution: "VFS Global expedited / employer urgency letter / nearby consulate",
      },
    ],
    xpReward: 100,
    badgeId: "visa_secured",
    lastVerified: "2026-04",
    verificationSource: "Claude general knowledge — REQUIRES expert review",
  },
  {
    id: "temporary_address",
    country: "DE",
    nameDe: "Vorübergehende Adresse",
    nameEn: "Temporary accommodation",
    description: "Have a place to live on day 1 where the landlord can issue a Wohnungsgeberbestätigung.",
    phase: "first-14-days",
    appliesWhen: { type: "always" },
    prerequisites: [],
    produces: ["temp_address"],
    deadline: { type: "after_arrival", days: 0 },
    processingTime: { minDays: 0, maxDays: 0 },
    locationDependent: false,
    costEur: 0,
    documentsRequired: [],
    escapePaths: [
      {
        id: "airbnb_wont_register",
        whenBlocked: "Hotels and Airbnbs typically refuse Wohnungsgeberbestätigung",
        resolution: "Use employer-provided temp flat, friend's apartment, or registration-friendly platforms (Wunderflats, Homelike).",
      },
    ],
    xpReward: 20,
    lastVerified: "2026-04",
    verificationSource: "Claude general knowledge — REQUIRES expert review",
  },
  {
    id: "anmeldung",
    country: "DE",
    nameDe: "Anmeldung",
    nameEn: "Address registration",
    description: "Register your address at the local Bürgeramt. Legally required within 14 days of moving in.",
    phase: "first-14-days",
    appliesWhen: { type: "always" },
    prerequisites: ["temporary_address"],
    produces: ["anmeldebestaetigung"],
    deadline: { type: "after_move_in", days: 14 },
    processingTime: { minDays: 0, maxDays: 1 },
    locationDependent: true,
    cityOverrides: [
      { city: "Berlin", appointmentWaitDays: { min: 28, max: 56 }, officeName: "Bürgeramt", bookingUrl: "https://service.berlin.de/dienstleistung/120686/" },
      { city: "Munich", appointmentWaitDays: { min: 14, max: 28 }, officeName: "KVR", bookingUrl: "https://www.muenchen.de/rathaus/terminvereinbarung_kvr.html" },
      { city: "Hamburg", appointmentWaitDays: { min: 0, max: 14 }, officeName: "Kundenzentrum", notes: "Walk-ins possible at some district offices" },
      { city: "Frankfurt", appointmentWaitDays: { min: 14, max: 28 }, officeName: "Bürgeramt" },
    ],
    costEur: 0,
    documentsRequired: [
      "Passport (and visa for non-EU)",
      "Wohnungsgeberbestätigung (signed by landlord)",
      "Rental contract (often requested)",
      "Anmeldeformular",
    ],
    escapePaths: [
      {
        id: "berlin_no_slots",
        whenBlocked: "No Bürgeramt slots within 14 days (common in Berlin)",
        resolution: "Document booking attempts. Authorities don't fine when slots are unavailable. Book earliest available.",
      },
    ],
    hrSync: {
      artifactsHrNeeds: ["anmeldebestaetigung"],
      uploadDeadlineDays: 3,
    },
    xpReward: 150,
    badgeId: "anmeldung_done",
    lastVerified: "2026-04",
    verificationSource: "Claude general knowledge — REQUIRES expert review",
  },
  {
    id: "online_bank",
    country: "DE",
    nameDe: "Online-Bankkonto",
    nameEn: "Online bank account",
    description: "Open an N26, Revolut, or Wise account before Anmeldung. Provides IBAN for first payroll.",
    phase: "first-14-days",
    appliesWhen: { type: "always" },
    prerequisites: ["temporary_address"],
    produces: ["iban_online"],
    deadline: { type: "before_first_payroll", days: 5 },
    processingTime: { minDays: 1, maxDays: 3 },
    locationDependent: false,
    costEur: 0,
    documentsRequired: ["Passport", "German address (any, including temp)"],
    escapePaths: [],
    hrSync: { artifactsHrNeeds: ["iban_online"], uploadDeadlineDays: 1 },
    xpReward: 50,
    lastVerified: "2026-04",
    verificationSource: "Claude general knowledge — REQUIRES expert review",
  },
  {
    id: "steuer_id",
    country: "DE",
    nameDe: "Steuer-ID",
    nameEn: "Tax ID",
    description: "11-digit lifetime tax ID, issued automatically after Anmeldung. Mailed to your registered address.",
    phase: "first-month",
    appliesWhen: { type: "always" },
    prerequisites: ["anmeldung"],
    produces: ["steuer_id_number"],
    deadline: { type: "before_first_payroll", days: 0 },
    processingTime: { minDays: 14, maxDays: 28 },
    locationDependent: false,
    costEur: 0,
    documentsRequired: [],
    escapePaths: [
      {
        id: "delayed_arrival",
        whenBlocked: "Steuer-ID not received before first payroll",
        resolution: "Employer runs payroll provisionally with Steuerklasse 6 (~42% emergency tax). Refunded retroactively when ID arrives. Normal.",
      },
    ],
    hrSync: { artifactsHrNeeds: ["steuer_id_number"], uploadDeadlineDays: 1 },
    xpReward: 60,
    lastVerified: "2026-04",
    verificationSource: "Claude general knowledge — REQUIRES expert review",
  },
  {
    id: "rundfunkbeitrag",
    country: "DE",
    nameDe: "Rundfunkbeitrag (GEZ)",
    nameEn: "Public broadcast fee",
    description: "Mandatory €18.36/month per household. They find you automatically via Anmeldung.",
    phase: "first-month",
    appliesWhen: { type: "always" },
    prerequisites: ["anmeldung"],
    produces: [],
    deadline: { type: "after_procedure", procedureId: "anmeldung", days: 90 },
    processingTime: { minDays: 14, maxDays: 90 },
    locationDependent: false,
    costEur: 220,
    documentsRequired: [],
    officialUrl: "https://www.rundfunkbeitrag.de/",
    escapePaths: [
      {
        id: "shared_household",
        whenBlocked: "Roommate already pays",
        resolution: "Submit Befreiung with their Beitragsnummer. Only one fee per household.",
      },
    ],
    xpReward: 20,
    lastVerified: "2026-04",
    verificationSource: "Claude general knowledge — REQUIRES expert review",
  },
  {
    id: "health_insurance_choice",
    country: "DE",
    nameDe: "Krankenversicherung wählen",
    nameEn: "Health insurance decision (GKV vs PKV)",
    description: "Choose between public (GKV) and private (PKV). One-way door for high earners — major long-term consequences.",
    phase: "first-month",
    appliesWhen: { type: "earns_above_threshold", thresholdEur: 69300 },
    prerequisites: [],
    produces: ["insurance_choice_decision"],
    deadline: { type: "after_arrival", days: 30 },
    processingTime: { minDays: 1, maxDays: 14 },
    locationDependent: false,
    costEur: 0,
    documentsRequired: [],
    escapePaths: [],
    isDecisionModule: true,
    xpReward: 80,
    badgeId: "informed_choice",
    notes: "DECISION MODULE — guide the user through comparison, don't just present a checkbox.",
    lastVerified: "2026-04",
    verificationSource: "Claude general knowledge — REQUIRES expert review",
  },
  {
    id: "gkv_enrollment",
    country: "DE",
    nameDe: "GKV-Anmeldung",
    nameEn: "Public health insurance enrollment",
    description: "Enroll with TK, AOK, Barmer, DAK, etc. Triggers Sozialversicherungsnummer.",
    phase: "first-month",
    appliesWhen: { type: "employment_in", values: ["employed"] },
    prerequisites: [],
    produces: ["gkv_membership"],
    deadline: { type: "before_first_payroll", days: 0 },
    processingTime: { minDays: 1, maxDays: 14 },
    locationDependent: false,
    costEur: 0,
    documentsRequired: ["Passport", "Employment contract", "Anmeldebestätigung (preferred)"],
    escapePaths: [],
    hrSync: { artifactsHrNeeds: ["gkv_membership"], uploadDeadlineDays: 2 },
    xpReward: 50,
    lastVerified: "2026-04",
    verificationSource: "Claude general knowledge — REQUIRES expert review",
  },
  {
    id: "sv_nummer",
    country: "DE",
    nameDe: "Sozialversicherungsnummer",
    nameEn: "Social security number",
    description: "12-character lifetime SV number, issued after first GKV enrollment.",
    phase: "first-month",
    appliesWhen: { type: "employment_in", values: ["employed"] },
    prerequisites: ["gkv_enrollment"],
    produces: ["sv_nummer"],
    deadline: { type: "before_first_payroll", days: 0 },
    processingTime: { minDays: 14, maxDays: 28 },
    locationDependent: false,
    costEur: 0,
    documentsRequired: [],
    escapePaths: [],
    hrSync: { artifactsHrNeeds: ["sv_nummer"], uploadDeadlineDays: 1 },
    xpReward: 30,
    lastVerified: "2026-04",
    verificationSource: "Claude general knowledge — REQUIRES expert review",
  },
  {
    id: "blue_card_app",
    country: "DE",
    nameDe: "Blaue-Karte-Antrag",
    nameEn: "Blue Card residence permit",
    description: "Convert your entry visa to a 4-year Blue Card residence permit at the Ausländerbehörde.",
    phase: "first-90-days",
    appliesWhen: {
      type: "and",
      clauses: [
        { type: "nationality_not_in", values: ["EU"] },
        { type: "has_visa_in", values: ["blue-card"] },
      ],
    },
    prerequisites: ["anmeldung"],
    softPrerequisites: ["steuer_id", "gkv_enrollment"],
    produces: ["blue_card_eat"],
    deadline: { type: "before_visa_expiry", days: 14 },
    processingTime: { minDays: 28, maxDays: 112 },
    locationDependent: true,
    cityOverrides: [
      {
        city: "Berlin",
        appointmentWaitDays: { min: 42, max: 112 },
        officeName: "LEA",
        bookingUrl: "https://otv.verwalt-berlin.de/ams/TerminBuchen",
        notes: "Book IMMEDIATELY upon arrival, not after Anmeldung.",
      },
    ],
    costEur: 100,
    documentsRequired: [
      "Passport", "Anmeldebestätigung", "Employment contract",
      "Salary proof", "GKV/PKV insurance proof", "Anabin/ZAB confirmation",
      "Biometric photo",
    ],
    escapePaths: [
      {
        id: "no_appointment",
        whenBlocked: "Cannot get appointment before 90-day visa expires",
        resolution: "Submit written Antrag by mail/email before expiry. Triggers Fiktionswirkung — you remain legal.",
      },
    ],
    hrSync: { artifactsHrNeeds: ["blue_card_eat"], uploadDeadlineDays: 7 },
    xpReward: 200,
    badgeId: "settled",
    lastVerified: "2026-04",
    verificationSource: "Claude general knowledge — REQUIRES expert review",
  },
  {
    id: "schufa",
    country: "DE",
    nameDe: "SCHUFA-Auskunft",
    nameEn: "SCHUFA credit record",
    description: "German credit history. Required by most landlords and some service providers.",
    phase: "first-90-days",
    appliesWhen: { type: "always" },
    prerequisites: ["anmeldung"],
    produces: ["schufa_auskunft"],
    deadline: { type: "none" },
    processingTime: { minDays: 1, maxDays: 14 },
    locationDependent: false,
    costEur: 30,
    documentsRequired: ["German address", "ID"],
    officialUrl: "https://www.meineschufa.de/",
    escapePaths: [
      {
        id: "empty_record",
        whenBlocked: "Just arrived — record will be empty",
        resolution: "Empty SCHUFA = 'no negative entries'. Combine with employer letter for stronger application.",
      },
    ],
    xpReward: 40,
    lastVerified: "2026-04",
    verificationSource: "Claude general knowledge — REQUIRES expert review",
  },
  {
    id: "permanent_apartment",
    country: "DE",
    nameDe: "Dauerhafte Wohnung",
    nameEn: "Long-term apartment",
    description: "Sign a long-term Mietvertrag and move out of temporary accommodation.",
    phase: "first-90-days",
    appliesWhen: { type: "always" },
    prerequisites: [],
    softPrerequisites: ["anmeldung", "schufa"],
    produces: ["mietvertrag"],
    deadline: { type: "none" },
    processingTime: { minDays: 7, maxDays: 56 },
    locationDependent: true,
    costEur: 0,
    documentsRequired: ["Passport", "Employment contract", "SCHUFA", "Bank statements"],
    escapePaths: [
      {
        id: "no_schufa",
        whenBlocked: "Need apartment before SCHUFA built up",
        resolution: "Get employer Bürgschaft / large deposit / SCHUFA-flexible platforms.",
      },
    ],
    xpReward: 100,
    badgeId: "rooted",
    lastVerified: "2026-04",
    verificationSource: "Claude general knowledge — REQUIRES expert review",
  },
  {
    id: "drivers_license",
    country: "DE",
    nameDe: "Führerschein-Umschreibung",
    nameEn: "Driving license conversion",
    description: "Convert foreign driver's license. Rules vary dramatically by country of origin.",
    phase: "first-6-months",
    // Any non-EU/EEA license needs at least an Umschreibung — exact rules
    // vary by Annex 11 country tier, but the procedure itself is universal.
    appliesWhen: {
      type: "or",
      clauses: [
        { type: "has_country_drivers_license", country: "IN" },
        { type: "has_country_drivers_license", country: "US" },
        { type: "has_country_drivers_license", country: "OTHER" },
      ],
    },
    prerequisites: ["anmeldung"],
    produces: ["german_drivers_license"],
    deadline: { type: "after_procedure", procedureId: "anmeldung", days: 180 },
    processingTime: { minDays: 14, maxDays: 180 },
    locationDependent: true,
    costEur: 200,
    documentsRequired: ["Original license", "Sworn translation", "Anmeldebestätigung", "Eye test", "First-aid certificate"],
    escapePaths: [
      {
        id: "missed_deadline",
        whenBlocked: "More than 6 months — driving without conversion is illegal",
        resolution: "Stop driving. Apply via full Fahrschule path.",
      },
    ],
    xpReward: 80,
    lastVerified: "2026-04",
    verificationSource: "Claude general knowledge — REQUIRES expert review",
  },
  {
    id: "annual_tax_return",
    country: "DE",
    nameDe: "Steuererklärung",
    nameEn: "Annual tax return",
    description: "Often produces refunds for arrival year (relocation costs are deductible).",
    phase: "first-year",
    appliesWhen: { type: "employment_in", values: ["employed", "freelance", "self-employed"] },
    prerequisites: ["steuer_id"],
    produces: ["steuerbescheid"],
    deadline: { type: "annual", month: 7, day: 31 },
    processingTime: { minDays: 30, maxDays: 180 },
    locationDependent: false,
    costEur: 0,
    documentsRequired: ["Lohnsteuerbescheinigungen", "Relocation receipts", "Insurance proofs"],
    escapePaths: [],
    xpReward: 60,
    lastVerified: "2026-04",
    verificationSource: "Claude general knowledge — REQUIRES expert review",
  },
];
